version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: swissbobo/backend-dev:v1
    ports:
      - ${BHOST_PORT}:${BCONT_PORT}
      - ${HOST_DEBUG}:${CONT_DEBUG}
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    env_file:
      - ./backend/env-docker/.dev.env
    command: "npm run dev"
    
  db:
    ports:
      - ${DBPORT_HOST}:${DBPORT_CONT}
    env_file:
      - ./backend/env-docker/.dbdev.env

  nginx:
    ports:
      - ${HOST_PORT}:${CONT_PORT}